[package]
name = "profiling"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.2"
tokio = { version = "1.47.1", features = ["full"] }
eframe = "0.30.0"
egui = "0.30.0"
egui_plot = "0.30.0"
